version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: codebuddy_dev
      POSTGRES_USER: codebuddy
      POSTGRES_PASSWORD: dev_password_change_in_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codebuddy"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass dev_redis_password
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://codebuddy:dev_password_change_in_prod@db:5432/codebuddy_dev
      - REDIS_URL=redis://:dev_redis_password@redis:6379/0
      - CELERY_BROKER_URL=redis://:dev_redis_password@redis:6379/0
      - SECRET_KEY=dev-secret-key-change-in-production
      - DJANGO_SETTINGS_MODULE=codebuddy.settings.development
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://codebuddy:dev_password_change_in_prod@db:5432/codebuddy_dev
      - REDIS_URL=redis://:dev_redis_password@redis:6379/0
      - CELERY_BROKER_URL=redis://:dev_redis_password@redis:6379/0
      - DJANGO_SETTINGS_MODULE=codebuddy.settings.development
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A codebuddy worker -l info

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://codebuddy:dev_password_change_in_prod@db:5432/codebuddy_dev
      - REDIS_URL=redis://:dev_redis_password@redis:6379/0
      - CELERY_BROKER_URL=redis://:dev_redis_password@redis:6379/0
      - DJANGO_SETTINGS_MODULE=codebuddy.settings.development
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A codebuddy beat -l info

volumes:
  postgres_data:
  static_volume:
  media_volume:
